apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vxlan-cni-ds
  namespace: kube-system
  labels:
    app: vxlan-cni
spec:
  selector:
    matchLabels:
      app: vxlan-cni
  template:
    metadata:
      labels:
        app: vxlan-cni
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: vxlan-cni-binary
        image: rajeevrmenon97/vxlan-cni:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: cni-dir
          mountPath: /host/opt/cni/bin
        command:
          - /bin/sh
          - "-c"
          - "sleep infinity"
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                cp /opt/cni/bin/vxlan /host/opt/cni/bin/
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                rm /host/opt/cni/bin/vxlan
      volumes:
      - name: cni-dir
        hostPath:
          path: /opt/cni/bin
